const allWords = [ 
    {en: "i am going to measure your speed",	ua: "Я измерю твою скорость"},
    {en: "looking forward to",	ua: "с нетерпением ожидая"},
    {en: "Rob my house",	ua: "Ограбить мой дом"},
    {en: "You don’t?",ua: 	"А ты не хочешь?"},
    {en: "Why don’t you cook dinner?",ua: 	"Почему ты не готовишь ужин?"},
    {en: "For real?",ua:  "	На самом деле? "},
    {en: "What about calling the police? It’s robbing",ua: 	"Что насчет звонка в полицию? Это ограбление"},
    {en: "like hell you are",ua: 	"черта с два ты"},
    {en: "if i get it running (I get it)",ua: 	"если я запущу его (я получу его)"},
    {en: "what's the point?",	ua: "А в чем смысл?"},
    {en: "i can't belive so lame even owned a bike like this.  (so lame)", ua: "Я не могу поверить, что у меня даже был такой мотоцикл.   (такой отстойный)"},
    {en: "i feel like this cover really says (like this)",ua: 	"я чувствую, что эта обложка действительно говорит (как это)"},
    {en: "quite", ua: "вполне"},
    {en: "opportunity",	ua: "возможность"},
    {en: "i could not turn it down (turn it down)",ua: 	"я не мог выключить его (выключить)"},
    {en: "i'm aware", ua: "я знаю"},
    {en: "i give up", ua: "я сдаюсь"},
    {en: "I can ride it", ua: "Я могу ездить на ней"},
    {en: "I was counting", ua: "on him	Я рассчитывал на него"},
    {en: "Come in home", ua: "Приходить домой"},
    {en: "Definition", ua: 	"Определение"},
    {en: "thank you all the same", ua: "(all the same)	спасибо всем вам одно и то же   (все равно)"},
    {en: "I am also keen on", ua: "Я тоже в восторге "},
    {en: "Get that bit out", ua: "Убрать эту часть"},
    {en: "essentially i can say okey?", ua:	"Я могу сказать хорошо?"},
    {en: "Determine", ua: "Определять"},
    {en: "You might to watch the attitude",	ua: "Вы могли бы следить за отношением"},
    {en: "Witch another way of saying we are poor",	ua: "Ведьма еще один способ сказать, что мы бедные"},
    {en: "and i'm quite capable of handing everything",	ua: "И я вполне способен дать все"},
    {en: "kind of", ua: "своего рода"},
    {en: "sort of", ua: "своего рода"},
    {en: "vacation", ua: "отпуск"},
    {en: "what brings you here", ua: "что привело тебя сюда"},
    {en: "near", ua: "вблизи"},
    {en: "Rude", ua: "Грубый"},
    {en: "You will figured it out", ua: "Ты разберешься с этим"},
    {en: "i ran into Sam", ua: "Я столкнулась с Сэмом"},
    {en: "Adorable", ua: "Очаровательный "},
    {en: "You cut those oranges into nice little wedges", ua: "Ты разрезаешь апельсины на милые маленькие клинья "},
    {en: "Was I wrong",	ua: "Был ли я неправ"},
    {en: "Responsible for human life", ua: "Ответственный за человеческую жизнь"},
    {en: "But no like you older", ua: "Но не так, как ты старше"},
    {en: "Don’t pray for any of em", ua: "Не молись ни за кого из них"},
    {en: "i kept the receipt", ua: "я сохранил квитанцию"},
    {en: "i have trained you well",	ua: "Я хорошо обучил тебя"},
    {en: "exponentially", ua: "экспоненциально"},
    {en: "If you wanna measure my iq", ua: "Если вы хотите измерить мой коэффициент интеллекта"},
    {en: "You are barking up the wrong tree", ua: "Ты лаешь не на то дерево"},
    {en: "well i will get just right to the point", ua: "Я перейду прямо к делу"},
    {en: "Sheldon is impressive addition", ua: "Шелдон - впечатляющее дополнение"},
    {en: "i didn't shake her hand", ua: "Я не пожимал ей руку"},
    {en: "i was brought to this school", ua: "Меня привели в эту школу"},
    {en: "You are barking up the wrong tree", ua: "Ты лаешь не на то дерево"},
    {en: "to put pressure on you", ua: "чтобы надавить на тебя"},
    {en: "to a lot of pressure on me", ua: "сильно давить на меня"},
    {en: "all the same", ua: "все равно"},
    {en: "i am also keen on", ua: "Я тоже в восторге"},
    {en: "overalls my ass", ua: "комбинезончик"},
    {en: "that basic particles", ua: "что основные частицы"},
    {en: "that make up reality", ua: "которые составляют реальность"},
    {en: "but i don't turn it on", ua: "но я не включаю его"},
    {en: "go ahead", ua: "давай"},
    {en: "leaping and dancing", ua: "прыжки и танцы"},
    {en: "did it work", ua: "сработало"},
    {en: "if i offer a stately bow", ua: "если я предложу величественный поклон"},
    {en: "haven't been to many wedding lately", ua: "не часто бывали на свадьбах в последнее время"},
    {en: "i happen to agree", ua: "Я с вами согласен"},
    {en: "funeral", ua: "похоронный"},
    {en: "furniture king", ua: "мебельный король"},
    {en: "i had an obligation",	ua: "у меня были обязательства"},
    {en: "and turned out fine", ua: "и все закончилось хорошо"},
    {en: "you owe her an apology", ua: "ты должен перед ней извиниться"},
    {en: "it turn out", ua: "оказывается"},
    {en: "well i will get just right to the point", ua: "Я перейду прямо к делу"},  
    {en: "Competition", ua: "Конкуренти"},
    {en: "Conversely", ua: "А з іншого боку"},
    {en: "Specific", ua: "Іменно"},
    {en: "Outside", ua: "Зовні"},
    {en: "Careful", ua: "Обежений"},
    {en: "Decisions", ua: "Рішення"},
    {en: "Rate ", ua: "Показаник"},
    {en: "Direction", ua: "Напрямок"},
    {en: "It was developed by SOMETHING in", ua: "Воно було розроблено кимось у якомусь"},
    {en: "Reusable", ua: "Перевикористовувані"},
    {en: "separately from the others", ua: "Віддільно від остальних"},
    {en: "Major advantages", ua: "Остновні переваги"},
    {en: "What are some of react limitation", ua: "Які є ліміти в реакті"},
    {en: "Solid", ua: "Міцний"},
    {en: "Is equal to", ua: "="},
    {en: "Add", ua: "+"},
    {en: "Subtract", ua: "-"},
    {en: "Variable", ua: "Змінна"},
    {en: "Announcement", ua: "Об'явлення"},
    {en: "will be carefully", ua: "буде обережно"},
    {en: "i salute you", ua: "я вітаю вас"},
    {en: "to fall out", ua: "випадати"},
    {en: "did you compose ", ua: "ти склав"},
    {en: "hurry up", ua: "поспішай"},
    {en: "apparently", ua: "мабуть"},
    {en: "complicated	", ua: "складний"},
    {en: "i tend to hurt women", ua: "Я схильний ображати жінок"},
    {en: "i suppose so	", ua: "я теж так думаю"},
    {en: "survival kit	", ua: "комплект для виживання"},
    {en: "i got confused ", ua: "я заплутався"},
    {en: "i don't recognize this place", ua: "я не впізнаю це місце"},
    {en: "why i bothering you", ua: "чому я тебе турбую"},
    {en: "i wanted to oppologize", ua: "я хотів вибачитися"},
    {en: "tent", ua: "намет"},
    {en: "when she worries about me	", ua: "коли вона турбується про мене"},
    {en: "ever", ua: "коли-небудь"},
    {en: "personally", ua: "особисто"},
    {en: "which is when i stopped shagging him", ua: "саме тоді я перестав з ним трахатися"},
    {en: "you are not supposed to stay friends with him	", ua: "ти не повинен залишатися з ним друзями"},
    {en: "i made the suggestion that i can to work myself	", ua: "я запропонував, що можу працювати сам"},
    {en: "advantage", ua: "перевага"},
    {en: "that's over", ua: "це закінчено"},
    {en: "i'm so aware of it", ua: "я так усвідомлюю це"},
    {en: "did you file your story", ua: "ти подав свою історію"},
    {en: "i never cheat on you", ua: "я ніколи не зраджую тобі"},
    {en: "Generally	", ua: "Загалом"},
    {en: "Everybody stirs tea the special spoon	", ua: "Кожен помішує чай спеціальною ложкою"},
    {en: "Carefully", ua: "Обережно"},
    {en: "Deploy", ua: "Розгорунти"},
    {en: "they'll survive", ua: "они выживут"},
    {en: "Escape", ua: "избежать"},
    {en: "it's no over", ua: "это не конец"},
    {en: "i was scary", ua: "Мені було страшно"},
    {en: "substitute", ua: "Заміна"},
    {en: "to the right of here", ua: "праворуч звідси"},
    {en: "three years ago i was banished", ua: "три роки тому мене вислали"},
    {en: "that came out wrong", ua: "що вийшло не так"},
    {en: "tide", ua: "припливу"},
    {en: "i'm afraid", ua: "Я боюся"},
    {en: "made up their mind", ua: "вирішили"},
    {en: "awesome", ua: "приголомшливий"},
    {en: "one hair out of place", ua: "одне волосся не на місці"},
    {en: "go ahead and glow it up", ua: "ідіть і запаліть його"},
    {en: "What are your purpose", ua: "Які ваші цілі"},
    {en: "apparently that you love her", ua: "мабуть, ти її любиш"},
    {en: "even though i was born blind", ua: "хоча я народився сліпим"},
    {en: "Even though", ua: "Незважаючи на"},
    {en: "actually, it's quite the other way around", ua: " На самом деле, это совсем другой способ"},
    {en: "I admit it", ua: "Я визнаю це"},
    {en: "what are your purpose", ua: "яка ваша мета"},
    {en: "all that time", ua: "весь цей час"},
    {en: "somehow", ua: "якось"},
    {en: "advance", ua: "заздалегідь"},
    {en: "it's time to resume your training", ua: "настав час відновити навчання"},
    {en: "but unfortunately for you", ua: "але на жаль для вас"},
    {en: "precise", ua: "точний"},
    {en: "separate", ua: "окремо"},
    {en: "brute", ua: "грубий"},
    {en: "i despise", ua: "я зневажаю"},
    {en: "i ate like a pig", ua: "я їв як свиня"},
];

const users = [
    {
        name: "oleg",
        surname: "salabay",
        email: "olegsalabaymac@gmail.com",
        photo: "",
        describe: "",
        password: "1234",
        role: "admin",
        dictionary: [],
    }
];

export {
    allWords,
    users
};

// {en: "please call me", ua: "будь ласка, зателефонуй мені"},
// {en: "from my point of you", ua: "з моєї точки зору вас"},
// {en: "with regard to", ua: "стосовно"},
// {en: "my best guess", ua: "моє найкраще припущення"},
// {en: "as far as i can see", ua: "наскільки я бачу"},
// {en: "besides", ua: "крім того"},
// {en: "despite", ua: "незважаючи"},
// {en: "based on", ua: "на основі"},
// {en: "capable of", ua: "здатний"},
// {en: "envious of", ua: "заздрить"},
// {en: "famous of", ua: "відомий з"},
// {en: "guilty of", ua: "винен у"},
// {en: "keen on", ua: "Захоплюється"},
// {en: "opposed to", ua: "на відміну від"},
// {en: "used to", ua: "звик до"},
// {en: "well done", ua: "молодець"},
// {en: "keep it up", ua: "так тримати"},
// {en: "that's better than ever", ua: "це краще, ніж будь -коли"},
// {en: "dont apologize", ua: "не вибачайтесь"},
// {en: "forget about it", ua: "забути про це"},
// {en: "miracle", ua: "диво"},
// {en: "passion", ua: "пристрасть"},
// {en: "disire", ua: "неспроможність"},
// {en: "in other words", ua: "іншими словами"},
// {en: "however", ua: "проте"},
// {en: "on the country", ua: "про країну"},
// {en: "after all", ua: "після всього"},
// {en: "to date", ua: "на сьогоднішній день"},
// {en: "assume", ua: "припустити"},
// {en: "there is", ua: "існує"},
// {en: "gotta be", ua: "повинен бути"},
// {en: "definitely", ua: "безумовно"},
// {en: "recently, i notice that", ua: "нещодавно я помітив це"},
// {en: "he is restrain", ua: "він стриманий"},
// {en: "one of them", ua: "один з них"},
// {en: "wake up", ua: "прокинься"},
// {en: "whatever", ua: "що завгодно"},
// {en: "something stange", ua: "щось стояти"},
// {en: "what is the benefit", ua: "яка користь"},
// {en: "refer", ua: "посилатися"},
// {en: "execute", ua: "виконувати"},
// {en: "communicated", ua: "спілкувалися"},
// {en: "consist", ua: "складатися"},
// {en: "examine", ua: "оглядати"},
// {en: "what kind of", ua: "якого типу"},
// {en: "to aassume", ua: "прийняти"},
// {en: "i notice", ua: "я помітив"},
// {en: "to restrain", ua: "стримувати"},
// {en: "ordinary", ua: "звичайний"},
// {en: "underdog", ua: "андердог"},
// {en: "to pick on", ua: "підбирати"},
// {en: "affection", ua: "прихильність"},
// {en: "if i were you", ua: "на твоєму місці"},
// {en: "long time no see", ua: "давно не бачились"},
// {en: "greit to see you", ua: "вітаю вас"},
// {en: "i am not being funny", ua: "я не смішний"},
// {en: "to be honest", ua: "чесно кажучи"},
// {en: "i would love but", ua: "я хотів би, але"},
// {en: "supposed you have", ua: "припустимо, що у вас є"},
// {en: "stab", ua: "колоти"},
// {en: "with pleasure", ua: "із задоволенням"},
// {en: "deprecated", ua: "застарілий"},
// {en: "he is suspect that", ua: "він підозрюється в цьому"},
// {en: "we will probably", ua: "ми напевно будемо"},
// {en: "we gotta go", ua: "ми маємо йти"},
// {en: "it looks desperat", ua: "виглядає відчайдушно"},
// {en: "incredible", ua: "неймовірний"},
// {en: "you should not have gone", ua: "ти не повинен був їхати"},
// {en: "converge on", ua: "сходитись далі"},
// {en: "rarely", ua: "рідко"},
// {en: "barely", ua: "ледве"},
// {en: "i needed out", ua: "мені потрібен був вихід"},
// {en: "i guess anywhere", ua: "я здогадуюсь де завгодно"},
// {en: "is that like", ua: "це схоже"},
// {en: "dont get me wrong", ua: "не зрозумійте мене неправильно"},
// {en: "how come", ua: "як так"},
// {en: "long story short", ua: "короткий розповідь"},
// {en: "did you ever thing that", ua: "ти коли небудь таке робив"},
// {en: "i realized", ua: "я зрозумів"},
// {en: "i moved out", ua: "я виїхав"},
// {en: "odd choice", ua: "непарний вибір"},
// {en: "it scare me", ua: "це мене лякає"},
// {en: "that is weird", ua: "це дивно"},
// {en: "in fact", ua: "фактично"},
// {en: "expessially", ua: "бездоганно"},
// {en: "i mention", ua: "я згадую"},
// {en: "i am impressed", ua: "я перебуваю під враженням"},
// {en: "appropriate", ua: "відповідний"},
// {en: "whole bunch", ua: "ціла купа"},
// {en: "litteraly", ua: "буквально"},
// {en: "i was sore the next day", ua: "наступного дня мені стало боляче"},
// {en: "advance", ua: "заздалегідь"},
// {en: "influence", ua: "впливати"},
// {en: "separate", ua: "окремі"},
// {en: "we'll", ua: "добре"},
// {en: "swept", ua: "підмітається"},
// {en: "nonverbal", ua: "невербальний"},
// {en: "actually", ua: "насправді"},
// {en: "wanna", ua: "хочу"},
// {en: "gonna", ua: "збираюся"},
// {en: "get away", ua: "втекти"},
// {en: "to be into something", ua: "займатися чимось"},
// {en: "mess with fate", ua: "возитися з долею"},
// {en: "relationship", ua: "відносини"},
// {en: "i am little uncomfortable with this anyway", ua: "мені все одно трохи неприємно від цього"},
// {en: "some good ones", ua: "кілька хороших"},
// {en: "i'm desperate, basically", ua: "я відчайдушно, в основному"},
// {en: "not in general", ua: "не загалом"},
// {en: "i realize that", ua: "я це усвідомлюю"},
// {en: "you swing for the fence. hold on aa second, Albert", ua: "ти розгойдуєшся за паркан. зачекайте секунду, Альберте"},
// {en: "That's good", ua: "Добре"},
// {en: "how ridiculous this is", ua: "як це смішно"},
// {en: "you know what it's like", ua: "ти знаєш, як це"},
// {en: "wrong", ua: "неправильно"},
// {en: "but at the same time", ua: "але водночас"},
// {en: "let's go paint that seiling", ua: "підемо пофарбувати це сідло"},
// {en: "take it easy", ua: "заспокойся"},
// {en: "On the one hand", ua: "З одного боку"},
// {en: "i thought  to ask", ua: "я думав запитати"},
// {en: "passion for", ua: "пристрасть до"},
// {en: "respond", ua: "відповідати"},
// {en: "samples", ua: "зразки"},
// {en: "we will run the whole lot of them by you", ua: "ми всі ними керуватимемо вами"},
// {en: "let is go over this one more time", ua: "давайте розглянемо це ще раз"},
// {en: "what is the objective", ua: "яка мета"},
// {en: "shock and awe", ua: "шок і трепет"},
// {en: "awful", ua: "жахливо"},
// {en: "exactly", ua: "саме"},
// {en: "handle", ua: "ручка"},
// {en: "to go over things", ua: "перебирати речі"},
// {en: "I going to buy a car there over", ua: "Я збираюся купити там машину"},
// {en: "occasionally", ua: "зрідка"}, 
// {en: "assist", ua: "допомагати"},
// {en: "complicate", ua: "ускладнювати"},
// {en: "collecte", ua: "збирати"},
// {en: "standardize", ua: "стандартизувати"},
// {en: "should go", ua: "повинен йти"},
// {en: "at the same time", ua: "в той самий час"},
// {en: "i feel obliged", ua: "я відчуваю себе зобов'язаним"},
// {en: "first crossed my mind", ua: "вперше прийшло в голову"},
// {en: "noting", ua: "відзначаючи"},
// {en: "introvert", ua: "інтроверт"},
// {en: "accross", ua: "навпроти"},
// {en: "right away", ua: "зразу"},
// {en: "assign", ua: "призначити"},
// {en: "available", ua: "доступний"},
// {en: "You should inform", ua: "Вам слід повідомити"},
// {en: "From time to time", ua: "Час від часу"},
// {en: "I turned on the dota", ua: "Я включив доту"},
// {en: "urgent", ua: "терміново"},
// {en: "Cool-headed", ua: "З холодною головою"},
// {en: "The fact is that", ua: "Справа в тому, що"},
// {en: "Evidence", ua: "Докази"},
// {en: "You should be honest with what is going on", ua: "Ви повинні бути чесними з тим, що відбувається"},
// {en: "You were busy with the emergency task", ua: "Ви були зайняті надзвичайним завданням"},
// {en: "You will apologies and prioritise this task.", ua: "Ви вибачитесь і визначите пріоритетність цього завдання"}, 
// {en: "what he thinks of proposed solution", ua: "що він думає про запропоноване рішення"},
// {en: "and it will be less time consuming than writing a long post.", ua: "і це займе менше часу, ніж написання довгого повідомлення"},
// {en: "Notifying the client on the time about your vacations and obligations", ua: "Повідомлення клієнта вчасно про ваші відпустки та обов’язки"},
// {en: "feature", ua: "функція"},
// {en: "in front of her", ua: "перед нею"},
// {en: "Plenty", ua: "Вдосталь"},
// {en: "and the essense the fact is", ua: "і суть в тому"},
// {en: "Frequently", ua: "зрідка"},
// {en: "such as what", ua: "наприклад що"},
// {en: "Playing football", ua: "Грати у футбол"},
// {en: "Before", ua: "Раніше"},
// {en: "However", ua: "Однак"}, 
// {en: "The most", ua: "Найбільший"},  
// {en: "on daily basis", ua: "на щоденній основі"},
// {en: "I am constantly thinking about you.", ua:	"Я постійно думаю про тебе"},
// {en: "how is it going?", ua: "Як справи?"},
// {en: "I owe to you", ua: "Я тобі винен"},
// {en: "My pleasure", ua: "Немає за що "},
// {en: "That reminds me", ua: "О згадав"},
// {en: "To ring a bell", ua: "Звучить знайомо"},
// {en: "Could you do me a favor?", ua: "Ти можеж мені помогти?"},
// {en: "It’s may be aa bit tricky", ua: "Це може бути трохи важко"},
// {en: "It was chatting to you!", ua: "Було приємно проговорити"},
// {en: "I gotta go!", ua: "Я маю йти"},
// {en: "Can’t complain", ua: "Не жаліюсь"},
// {en: "I am constantly thinking about you", ua: "And measure Я постоянно думаю о тебе"},
// {en: "how is it going?",ua: 	"Как у вас дела?"},
// {en: "Everything I now possess, I owe to you.",ua: "Все, чем я сейчас обладаю, я обязан тебе."},
// {en: "My pleasure",	ua: "Мое удовольствие"},
// {en: "That reminds me, I must post that letter.", ua: "Это напомнило мне, что я должен отправить это письмо."},
// {en: "To ring a bell",ua: 	"Колокол"},
// {en: "Could you do me a favor?",ua: "Можешь сделать мне одолжение? "},
// {en: "It’s may be a bit tricky",ua: "Это может быть немного сложно"},
// {en: "It was chatting to you!",ua: "Он разговаривал с тобой!"},
// {en: "I gotta go!",ua: "Я должен идти, Дживс!"},
// {en: "Can’t complain",ua: "Не могу жаловаться"},
// {en: "Destroy", ua: "Знищити"},
// {en: "Adventure", ua: "Пригоди"},
// {en: "Predict", ua: "Передбачити"},
// {en: "Produce", ua: "Виробляти"},
// {en: "Complete", ua: "Повна"},
// {en: "Truly", ua: "Воістину"},
// {en: "Burst", ua: "Вибух"},
// {en: "Supply", ua: "Постачання"},
// {en: "Instead", ua: "Натомість"},
// {en: "Spare", ua: "Запасний"},
// {en: "At once", ua: "Якось"},
// {en: "Explode", ua: "Вибухнути"},
// {en: "Literally", ua: "Буквально"},
// {en: "Spy", ua: "Шпигун"},
// {en: "Closer", ua: "Ближче"},
// {en: "Stab", ua: "Колоти"},
// {en: "Court", ua: "Суд"},
// {en: "Goal", ua: "Гол"},
// {en: "Worn", ua: "Зношені"},
// {en: "Observe", ua: "Спостерігати"},
// {en: "Impatient", ua: "Нетерплячий"},
// {en: "evidence", ua: "Свідчення"},
// {en: "Flare", ua: "Спалах"},
// {en: "Blame", ua: "Винуватий"},
// {en: "Threat", ua: "Загроза"},
// {en: "Trail", ua: "Стежка"},
// {en: "Respect", ua: "Повага"},
// {en: "Fool", ua: "Дурень"},
// {en: "Escape", ua: "Втеча"},
// {en: "Sake", ua: "Користь"},
// {en: "Reveal", ua: "Розкрити"},
// {en: "Coward", ua: "Боягуз"},
// {en: "Proud", ua: "Гордий"},
// {en: "Admit", ua: "Визнати"},
// {en: "Pure", ua: "Чистий"},
// {en: "Cooperate", ua: "Співпрацювати"},
// {en: "Eventually", ua: "Зрештою"},
// {en: "Solve", ua: "Розв’язати"},
// {en: "Envy", ua: "Заздрість"},
// {en: "Regret", ua: "Шкода"},
// {en: "Obviously", ua: "Очевидно"},
// {en: "Apparently", ua: "Мабуть"},
// {en: "Evil", ua: "Зло"},
// {en: "Rush", ua: "Поспіх"},
// {en: "Employ", ua: "Працевлаштування"},
// {en: "Dire", ua: "Страшно"},
// {en: "Consequence", ua: "Наслідок"},
// {en: "Spans", ua: "Прольоти"},
// {en: "Able", ua: "Здатний"},
// {en: "Barely", ua: "Ледве"},
// {en: "Deliver", ua: "Доставити"},
// {en: "Rely", ua: "Вірити"},
// {en: "Honey", ua: "Мед"},
// {en: "Mock", ua: "Макет"},
// {en: "Betray", ua: "Зрада"},
// {en: "Get on", ua: "Вступайте"},
// {en: "Trust", ua: "Довіра"},
// {en: "Steer", ua: "Рульове управління"},
// {en: "Demand", ua: "Попит"},
// {en: "Cost", ua: "Вартість"},
// {en: "Pleasure", ua: "Задоволення"},
// {en: "Edit", ua: "Редагувати"},
// {en: "Case", ua: "Футляр"},
// {en: "Template", ua: "Шаблон"},
// {en: "Give up", ua: "Здаватися"},
// {en: "Robber", ua: "Розбійник"},
// {en: "Suddenly", ua: "Раптом"},
// {en: "Separate", ua: "Окремі"},
// {en: "Dest", ua: "Доля"},
// {en: "Primarily", ua: "Насамперед"},
// {en: "Barely", ua: "Ледве"},
// {en: "trap", ua: "ловушка"},
// {en: "Shelter", ua: "Укриття"},
// {en: "Hang", ua: "Повісити"},
// {en: "around", ua: "навколо"},
// {en: "Surround", ua: "Об'ємне звучання"},
// {en: "Instant", ua: "Миттєвий"},
// {en: "Lick", ua: "Лизати"},
// {en: "Chill out", ua: "Розслабся"},
// {en: "Sprain", ua: "Розтягнення"},
// {en: "Exact", ua: "Точний"},
// {en: "To sum up", ua: "Підсумовуючи"},
// {en: "Stare at", ua: "Дивитися на"},
// {en: "Advert", ua: "Реклама"},
// {en: "Bumb", ua: "Бум"},
// {en: "into", ua: "в"},
// {en: "Get into", ua: "Залазь"},
// {en: "Stuffy", ua: "в'язкий"},
// {en: "Crave", ua: "Жадати"},
// {en: "Confuse", ua: "Плутати"},
// {en: "Elect", ua: "Обраний"},
// {en: "Enforce", ua: "Примусити"},
// {en: "Impress", ua: "Вразити"},
// {en: "Struggle", ua: "Боротьба"},
// {en: "Compulsory", ua: "Обов’язковий"},
// {en: "Climb", ua: "Підйом"},
// {en: "Cliff", ua: "Скеля"},
// {en: "Base", ua: "База"},
// {en: "Camp", ua: "Табір"},
// {en: "Admire", ua: "Захоплюватися"},
// {en: "Sight", ua: "Зір"},
// {en: "Recover", ua: "Відновити"},
// {en: "Vomit", ua: "Блювота"},
// {en: "Fever", ua: "Лихоманка"},
// {en: "Herbar", ua: "Гербар"},
// {en: "Dizzy", ua: "Запаморочення"},
// {en: "Injection", ua: "Ін'єкції"},
// {en: "Busy", ua: "Зайнято"},
// {en: "Dedicate", ua: "Присвячувати"},
// {en: "Prescribe", ua: "Призначити"},
// {en: "Receive", ua: "Отримувати"},
// {en: "Invent", ua: "Винайти"},
// {en: "Average", ua: "Середній"},
// {en: "Aware", ua: "Усвідомлений"},
// {en: "Confuse", ua: "Плутати"},
// {en: "Daily", ua: "Щоденно"},
// {en: "Shout", ua: "Кричати"},
// {en: "Tend", ua: "Схильні"},
// {en: "Lean", ua: "Пісний"},
// {en: "Quilt", ua: "Ковдра"},
// {en: "Wide", ua: "Широкий"},
// {en: "Rude", ua: "Грубо"},
// {en: "Consider", ua: "Поміркуйте"},
// {en: "Faced", ua: "Зіткнувся"},
// {en: "Permit", ua: "Дозвіл"},
// {en: "Occurs", ua: "Виникає"},
// {en: "Apply", ua: "Застосувати"},
// {en: "Hybrid", ua: "Гібридний"},
// {en: "Assume", ua: "Припустимо"},
// {en: "Aligned", ua: "Вирівняно"},
// {en: "Volume", ua: "Обсяг"},
// {en: "Motion", ua: "Рух"},
// {en: "Impact", ua: "Вплив"},
// {en: "Because Of Me", ua: "Через мене"},
// {en: "Actually", ua: "Власне"},
// {en: "Inspect", ua: "Оглянути"},
// {en: "Enture", ua: "Підприємство"},
// {en: "Impression", ua: "Враження"},
// {en: "The same", ua: "Той самий"},
// {en: "Quite", ua: "Цілком"},
// {en: "Reject", ua: "Відхилити"},
// {en: "Absent", ua: "Відсутній"},
// {en: "Occurs", ua: "Виникає"},
// {en: "Woolly", ua: "Вовняний"},
// {en: "Hybrid", ua: "Гібридний"},
// {en: "There for", ua: "Там для"},
// {en: "Hence", ua: "Отже"},
// {en: "Indeed", ua: "Дійсно"},
// {en: "Generally", ua: "Загалом"},
// {en: "Besides", ua: "Крім того"},
// {en: "In spite of", ua: "Попри"},
// {en: "As a rule", ua: "Як правило"},
// {en: "Freak", ua: "Виродка"},
// {en: "Calm down", ua: "Заспокойся"},
// {en: "Never mina", ua: "Ніколи не міна"},
// {en: "I mean", ua: "Я маю на увазі"},
// {en: "For real", ua: "Насправді"},
// {en: "Like what", ua: "Як що"},
// {en: "Cheer", ua: "Вболівати"},
// {en: "Get in", ua: "Залазь"},
// {en: "Holds", ua: "Тримає"},
// {en: "On time", ua: "Вчасно"},
// {en: "Scary", ua: "Страшно"},
// {en: "Fellow", ua: "Товариш"},
// {en: "Gather", ua: "Збирати"},
// {en: "Duties", ua: "Обов’язки"},
// {en: "Vary", ua: "Варіація"},
// {en: "Income", ua: "Дохід"},
// {en: "Profit", ua: "Прибуток"},
// {en: "Decade", ua: "Десятиліття"},
// {en: "Burnt", ua: "Вигоріла"},
// {en: "To note", ua: "Занотовувати"},
// {en: "Shape", ua: "Форма"},
// {en: "Restock", ua: "Поповнення запасів"},
// {en: "Amount", ua: "Сума"},
// {en: "Extreme", ua: "Екстремальний"},
// {en: "Source", ua: "Джерело"},
// {en: "Conversation", ua: "Бесіда"},
// {en: "Average", ua: "Середній"},
// {en: "Obtain", ua: "Отримати"},
// {en: "Arrange", ua: "Влаштувати"},
// {en: "Blind", ua: "Сліпий"},
// {en: "Wage", ua: "Заробітна плата"},
// {en: "Rural", ua: "Сільський"},
// {en: "Goal", ua: "Гол"},
// {en: "Approach", ua: "Підхід"},
// {en: "Pull", ua: "Потягнути"},
// {en: "Undo", ua: "Скасувати"},
// {en: "Redo", ua: "Повторити"},
// {en: "Comit", ua: "Комітет"},
// {en: "Examine", ua: "Вивчити"},
// {en: "Request", ua: "Запит"},
// {en: "Ref", ua: "Посилання"},
// {en: "Consistent", ua: "Послідовний"},
// {en: "Bundle", ua: "Пачка"},
// {en: "Trial", ua: "Випробування"},
// {en: "Affirm", ua: "Підтвердити"},
// {en: "Such", ua: "Такі"},
// {en: "Special", ua: "Спеціальні"},
// {en: "adjust", ua: "коригувати"},
// {en: "charm", ua: "чарівність"},
// {en: "merger", ua: "злиття"},
// {en: "move", ua: "рухатися"},
// {en: "embody", ua: "втілювати"},
// {en: "baffled", ua: "збентежений"},
// {en: "don't worry", ua: "не хвилюйтесь"},
// {en: "time has passed", ua: "час минув"},
// {en: "press", ua: "прес"},
// {en: "produce", ua: "виробляти"},
// {en: "approve", ua: "схвалювати"},
// {en: "deploy", ua: "розгорнути"},
// {en: "conversation", ua: "розмова"},
// {en: "intersection", ua: "перехрестя"},
// {en: "customize", ua: "налаштувати"},
// {en: "reproduce", ua: "відтворювати"},
// {en: "quickly", ua: "швидко"},
// {en: "decition", ua: "постановлення"},
// {en: "anable", ua: "анаболічний"},
// {en: "mention", ua: "згадка"},
// {en: "metric", ua: "метричні"},
// {en: "comper", ua: "компер"},
// {en: "regarding", ua: "стосовно"},
// {en: "becomes", ua: "стає"},
// {en: "publisher", ua: "видавець"},
// {en: "immpresion", ua: "імпресія"},
// {en: "sentually", ua: "посланний"},
// {en: "mock", ua: "макет"},
// {en: "difficult", ua: "важко"},
// {en: "generally", ua: "загалом"},
// {en: "quickly", ua: "швидко"},
// {en: "decition", ua: "постановлення"},
// {en: "mention", ua: "згадка"},
// {en: "compare", ua: "порівнювати"},
// {en: "regarding", ua: "стосовно"},
// {en: "becomes", ua: "стає"},
// {en: "publisher", ua: "видавець"},
// {en: "immpretion", ua: "імпресія"},
// {en: "mock", ua: "макет"},
// {en: "difficult", ua: "важко"},
// {en: "generally", ua: "загалом"},
// {en: "imoleament", ua: "підживлення"},
// {en: "compale", ua: "ущільнювати"},
// {en: "simmilar", ua: "подібний"},
// {en: "compatible", ua: "сумісні"},
// {en: "divide", ua: "розділити"},
// {en: "relate", ua: "пов'язувати"},
// {en: "terrain", ua: "місцевість"},
// {en: "customizable", ua: "настроюється"},
// {en: "enhancements", ua: "покращення"},
// {en: "layer", ua: "шар"},
// {en: "horizon", ua: "горизонт"},
// {en: "fog", ua: "туман"},
// {en: "Invalid", ua: "Недійсний"},
// {en: "assignment", ua: "призначення"},
// {en: "occur", ua: "відбуваються"},
// {en: "toggle-baselayers", ua: "перемикачі-базові шари"},
// {en: "baselayer", ua: "базовий шар"},
// {en: "referre", ua: "направити"},
// {en: "deprecate", ua: "знецінити"},
// {en: "in favor", ua: "на користь"},
// {en: "Internally", ua: "Внутрішньо"},
// {en: "plainly", ua: "однозначно"},
// {en: "snippet", ua: "фрагмент"},
// {en: "hit", ua: "удар"},
// {en: "repetitive", ua: "повторювані"},
// {en: "nullish", ua: "нульовий"},
// {en: "proposal", ua: "пропозиція"},
// {en: "toggler", ua: "перемикач"},
// {en: "posibility", ua: "можливість"},
// {en: "impleament", ua: "реалізація"},
// {en: "doesn't", ua: "не робить"},
// {en: "matter", ua: "матерія"},
// {en: "generally", ua: "загалом"},
// {en: "prefix", ua: "префікс"},
// {en: "abvious", ua: "відсутня"},
// {en: "diff", ua: "різниця"},
// {en: "represents", ua: "представляє"},
// {en: "exposes", ua: "викриває"},
// {en: "bearing", ua: "підшипник"},
// {en: "hash", ua: "хеш"},
// {en: "fired", ua: "звільнений"},
// {en: "idle", ua: "простою"},
// {en: "pointing", ua: "вказування"},
// {en: "rotate", ua: "обертати"},
// {en: "fit", ua: "підходить"},
// {en: "bounds", ua: "межі"},
// {en: "terrain", ua: "місцевість"},
// {en: "repaint", ua: "перефарбувати"},
// {en: "handling", ua: "поводження"},
// {en: "logger", ua: "лісоруб"},
// {en: "Square", ua: "Майдан"},
// {en: "Discast", ua: "Розповсюдження"},
// {en: "capture", ua: "захоплення"},
// {en: "recognize", ua: "впізнати"},
// {en: "execute", ua: "виконувати"},
// {en: "dispense", ua: "дозувати"},
// {en: "monetary", ua: "грошові"},
// {en: "built in", ua: "вбудований"},
// {en: "record", ua: "запис"},
// {en: "we got", ua: "ми отримали"},
// {en: "what we do", ua: "що ми робимо"},
// {en: "what makes all the difference", ua: "у чому різниця"},
// {en: "horrible", ua: "жахливо"},
// {en: "terrible", ua: "страшний"},
// {en: "taste", ua: "смак"},
// {en: "to buzz", ua: "гудіти"},
// {en: "buzz him in", ua: "ввімкніть його"},
// {en: "he finnaly", ua: "він нарешті"},
// {en: "to ask me", ua: "спитати мене"},
// {en: "in other words", ua: "іншими словами"},
// {en: "more", ua: "більше"},
// {en: "less", ua: "менше"},
// {en: "what you think is less important", ua: "те, що ви вважаєте менш важливим"},
// {en: "confident", ua: "впевнений у собі"},
// {en: "is there a defference between you and me?", ua: "чи є різниця між вами та мною ?"},
// {en: "self-help", ua: "самодопомога"},
// {en: "availabel", ua: "доступний"},
// {en: "inreality", ua: "в реальності"},
// {en: "to matter", ua: "мати значення"},
// {en: "where is the?", ua: "де є?"},
// {en: "let is go to", ua: "let is to to"},
// {en: "how much is this", ua: "скільки це коштує"},
// {en: "hungry", ua: "голодний"},
// {en: "what time is it", ua: "котра година"},
// {en: "could be worse", ua: "могло бути гірше"},
// {en: "could be better", ua: "могло б бути краще"},
// {en: "in general! not bad", ua: "загалом! непогано"},
// {en: "i was learnt", ua: "мене навчили"},
// {en: "never better", ua: "ніколи краще"},
// {en: "what dows this word mean", ua: "що означає це слово"},
// {en: "that sound greate", ua: "це чудово звучить"},
// {en: "that suks", ua: "що смокче"},
// {en: "hold on", ua: "Зачекай"},
// {en: "lets have some", ua: "давайте трохи"},
// {en: "i down", ua: "i вниз"},
// {en: "queue", ua: "черга"},
// {en: "for shure!", ua: "за шуре !"},
// {en: "i will you miss to", ua: "я буду сумувати за тобою"},
// {en: "to be here on time", ua: "бути вчасно"},
// {en: "to inform you", ua: "повідомити вас"},
// {en: "this is nonsense", ua: "це нісенітниця"},
// {en: "clearly", ua: "чітко"},
// {en: "this is your fault", ua: "це твоя провина"},
// {en: "but you leave me no choice", ua: "але ти не залишаєш мені вибору"},
// {en: "you will regret this", ua: "ви пошкодуєте про це"},
// {en: "you are a brave", ua: "ти сміливий"},
// {en: "those are actually", ua: "це насправді"},
// {en: "that comes from", ua: "що походить від"},
// {en: "it is pleasure", ua: "це задоволення"},
// {en: "hopefully", ua: "сподіваюся"},
// {en: "introduction", ua: "введення"},
// {en: "i couldn't make", ua: "я не міг зробити"},
// {en: "would you like to have some", ua: "ти хотів би мати"},
// {en: "that is nice", ua: "це мило"},
// {en: "we will probably", ua: "ми напевно будемо"},
// {en: "i am just glad", ua: "я просто радий"},
// {en: "it went really well", ua: "це пройшло дуже добре"},
// {en: "conclusion", ua: "висновок"},
// {en: "this article", ua: "Ця стаття"},
// {en: "those", ua: "ті"},